export const studioTheme = {
  color: {
    background: "#F8FAFC",
    surface: "#FFFFFF",
    surfaceMint: "#F6FBFA",
    sidebar: "#ECFDF5",
    primary: "#0F766E",
    primaryStrong: "#115E59",
    primarySoft: "#CCFBF1",
    action: "#A5B4FC",
    actionStrong: "#818CF8",
    actionSoft: "#EEF2FF",
    actionStart: "#99F6E4",
    actionEnd: "#C4B5FD",
    info: "#2563EB",
    text: "#102033",
    muted: "#64748B",
    border: "#DBE7E8",
    borderSoft: "#EAF2F3",
  },
  radius: {
    control: "8px",
    card: "10px",
    panel: "12px",
  },
} as const;
